services:
  tarefasflow_landing:
    image: ghcr.io/cleitonpcarvalho/tarefasflow-landing:latest
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
    networks:
      - AutomaNet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=AutomaNet"
        - "traefik.http.routers.tarefasflow-landing.rule=Host(`tarefasflow.com.br`)"
        - "traefik.http.routers.tarefasflow-landing.entrypoints=websecure"
        - "traefik.http.routers.tarefasflow-landing.tls=true"
        - "traefik.http.routers.tarefasflow-landing.tls.certresolver=letsencrypt"
        - "traefik.http.services.tarefasflow-landing.loadbalancer.server.port=3000"

networks:
  AutomaNet:
    external: true
